# Generated by Django 4.1 on 2024-11-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_rename_contact_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(),
        ),
    ]
